version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_container_nextjs_capabletech
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mytestdb
    ports:
      - "5432:5432" # default port currently
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
